Feat/feature engineering v1
spirabr/SPIRA-training pull request #13
Opened 2024-09-15 20:19 UTC by lucasqml

2024-09-16 13:57 UTC, bolgheroni requested changes

2024-09-16 13:57 UTC, bolgheroni commented on src/spira_training/shared/ports/valid_path_reader.py
> +    def read_valid_paths(self, path: ValidPath) -> List[ValidPath]:
qual a logica disso? voce recebe um path, e retorna uma lista de paths?

2024-09-16 13:57 UTC, bolgheroni commented on src/spira_training/shared/core/models/valid_path.py
> +        raise FileExistsError(f"File {path} does not exist.")
nao curti muito essa mistura... class methods, funcoes auxiliares... nao entendi pra que tem a classe ValidPath

2024-09-16 13:57 UTC, bolgheroni commented on src/spira_training/shared/core/services/feature_engineering_service.py
> +        controls_inputs = self._load_audio_data(self.config.audio.dataset_paths.controls_csv)
apesar de vc criar a abstracao de ValidPathReader, aqui vc ta recebendo direto um path pra um csv...

2024-09-16 13:57 UTC, bolgheroni commented on src/spira_training/shared/core/services/feature_engineering_service.py
> +
pq ta redefinindo a AudiosRepository?

2024-09-16 13:58 UTC, bolgheroni commented
nao tem testes tambem

2024-09-16 14:06 UTC, lucasqml commented on src/spira_training/shared/core/services/feature_engineering_service.py
> +
opa, aqui foi a IDE que corrigiu automaticamente
subi o fix

2024-09-25 23:30 UTC, bolgheroni commented on src/spira_training/shared/ports/path_validator.py
> +class PathValidator(ABC):
voce seguiu com essa abordagem entao?

2024-09-25 23:30 UTC, bolgheroni commented on src/spira_training/shared/core/services/feature_engineering_service.py
> +        patients_inputs, controls_inputs, noises = self._load_data()
aqui nao ta usando ainda ne

2024-09-25 23:30 UTC, bolgheroni commented on src/spira_training/apps/feature_engineering/configs/audio_processor_config.py
pra que serve isso aqui?

2024-09-25 23:30 UTC, bolgheroni commented on src/spira_training/apps/feature_engineering/configs/audio_processor_config.py
pq nao usar um enum?

2024-09-25 23:30 UTC, bolgheroni commented on src/spira_training/apps/feature_engineering/configs/audio_processor_config.py
> +
pra q precisou disso tb?

2024-09-25 23:30 UTC, bolgheroni commented on tests/fakes/fake_path_validator.py
> +        return path
podia mudar a interface pra receber uma string e retornar um valid path, acho q ficava melhor ne?

2024-09-25 23:30 UTC, bolgheroni commented on src/spira_training/shared/ports/path_validator.py
> +class PathValidator(ABC):
poderia receber string tambem alem de Path, ne?

2024-09-26 00:41 UTC, lucasqml commented on src/spira_training/shared/ports/path_validator.py
> +class PathValidator(ABC):
fazer um union na tipagem vc diz?

2024-09-26 00:44 UTC, lucasqml commented on src/spira_training/shared/core/services/feature_engineering_service.py
> +        patients_inputs, controls_inputs, noises = self._load_data()
ainda não, tava refletindo sobre o path que é passado pro dataset_repository.

2024-09-26 00:56 UTC, lucasqml commented on src/spira_training/apps/feature_engineering/configs/audio_processor_config.py
serve pra definir variavel de classe pro pydantic, que ai pode ser acessado por qlq instancia da classe tipo AudioProcessorType.MFCC

não tinha usado o enum pra manter o padrão de usar o BaseModel

2024-09-26 01:05 UTC, lucasqml commented on src/spira_training/apps/feature_engineering/configs/audio_processor_config.py
> +
tava tendo erro pra instanciar os fakes das configs, ai coloquei pra ajudar nos testes esqueci de tirar, vou remover

2024-09-26 01:18 UTC, lucasqml commented on src/spira_training/shared/ports/path_validator.py
> +class PathValidator(ABC):
fazer um ou na tipagem vc diz?

2024-09-26 22:18 UTC, bolgheroni commented on src/spira_training/shared/ports/path_validator.py
> +class PathValidator(ABC):
acho q funcionaria ne

2024-09-27 13:39 UTC, bolgheroni approved these changes

2024-09-27 13:39 UTC, bolgheroni commented on src/spira_training/apps/feature_engineering/configs/audio_processor_config.py
eh q vc ta usando uma classe pra definir os tipos possiveis, seila achei bem estranho

2024-09-27 17:54 UTC, merged